twitch:
  irc_token: "your_twitch_irc_token"
  client_id: "your_twitch_client_id"
  nick: "your_bot_nick"
  prefix: "!"
  initial_channels:
    - "your_channel_name"

obs:
  obs_path: "C:/Program Files/obs-studio/bin/64bit/obs64.exe"

steam:
  steam_path: "C:/Program Files (x86)/Steam"
